kind: Deployment
apiVersion: apps/v1
metadata:
  name: sqldata
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: sqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sqldata
  template:
    metadata:
      labels:
        app: eshop
        service: sqldata
    spec:
      containers:
        - name: sqldata
          image: postgres:13-bullseye
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres

---

kind: Service
apiVersion: v1
metadata:
  name: sqldata
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: sqldata
spec:
  type: NodePort
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 31433
      protocol: TCP
      name: tds
  selector:
    service: sqldata
